name: "MacOS sign installer action"
description: "Sign macOS .pkg installer"

inputs:
  unsigned-pkg-path:
    description: "Path to .pkg installer"
    required: true
  signed-pkg-path:
    description: "Path to .pkg installer"
    required: true
  mac-keychain-pass:
    description: "Password for keychain"
    required: true
  mac-installer-certkey:
    description: "Base64 encoded .p12 certificate and key"
    required: true
  mac-certkey-pass:
    description: "Password for .p12 certificate and key"
    required: true

runs:
  using: "composite"

  steps:
    - name: Check for Keychain
      id: check_keychain
      shell: bash
      run: |
        if security list-keychains | grep -q "build.keychain"; then
          echo "keychain_exists=true" >> $GITHUB_OUTPUT
        else
          echo "keychain_exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Create keychain
      if: steps.check_keychain.outputs.keychain_exists == 'false'
      shell: bash
      run: |
        security create-keychain -p "${{ inputs.mac-keychain-pass }}" build.keychain
        echo "Keychain created"
        security set-keychain-settings -lut 21600 build.keychain
        echo "Keychain settings set"
        security default-keychain -s build.keychain
        echo "Keychain made default"
        security unlock-keychain -p "${{ inputs.mac-keychain-pass }}" build.keychain
        echo "Keychain unlocked"

    - name: Import certificates
      shell: bash
      run: |
        echo "${{ inputs.mac-installer-certkey }}" | base64 --decode > installer_certkey.p12

        security import ./installer_certkey.p12 \
          -k build.keychain \
          -f pkcs12 \
          -P "${{ inputs.mac-certkey-pass }}" \
          -T /usr/bin/codesign \
          -T /usr/bin/productsign

    - name: Allow codesign and productsign to use keychain
      shell: bash
      run: |
        security set-key-partition-list \
          -S apple-tool:,apple:,codesign:,productsign: \
          -s \
          -k "${{ inputs.mac-keychain-pass }}" \
          build.keychain

    - name: Sign contents
      shell: bash
      run: |
        productsign \
           --timestamp \
           --sign "Developer ID Installer" \
           "${{ inputs.unsigned-pkg-path }}" \
           "${{ inputs.signed-pkg-path }}"
